apiVersion: v1
kind: Secret
metadata:
    name: metrics-grafana
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:4zM2UZ8=,iv:FeapoJqgomyLFWLznYi+0iN+FPI7+xnYiv5nMyCQU74=,tag:u+UB9xETUNNAnlZtXwEWoA==,type:str]
    admin-password: ENC[AES256_GCM,data:hFGadQmlAnoFsorSXVAmMwvapdbpHQdfSNuqfN0ebes=,iv:382yityklPt/RaGVdRBP4/GYO6U4qzzh1nmz20Nd3g8=,tag:Vfr6+v5km1qRZdP1Jl48ww==,type:str]
    ldap-toml: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTUZ1WHR6dHJxcGFCcDBi
            enordituMDBwcUg4RytvdWI3R05NRGtiVFRjCk1jQTA0QjRVWG1scEx3cnJSa2Q5
            NGhodUo2enJGMnIwalpkR2p5Unlha00KLS0tIHVvcVQxRFp1WVZadnc1bWN1SXVG
            bU82WjBIYlNxNlZZd0dZZmFZeGx2RzgKumKYvm+n/3jEqw6CnLHm2OJW4JFiUgZU
            77OMDxT9R/3ckyCHx7yGYnVFw5ack+9bbTNHDOO8wDWyYyR83hOPLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10j22qkq3gxn7779zyle9d4segrhstevjtjmw8hh0e488qzfu3cpskld2ey
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T22:02:24Z"
    mac: ENC[AES256_GCM,data:xUArZ/t+rUfXjHQKE/+JNteueLe0ScMmuqM5cP8j2o9tKYxao9ZC25snvOtH9tZALK/z4o9jmyUu7HZcpcGPyKUJ47mNzjybcJ69AXJt7Zjku+5yJJPjPXfv8h6Qlmjkm2SLs3kX+Ei1kgIV9EseGZYQUqA5faXSIhRo0xr72Jc=,iv:4IYTfTxDH1368mtGdbldpcti00QQwapTpJheqN4bm9M=,tag:Ug/YVRWrwmj2aLcniBh2/g==,type:str]
    version: 3.13.3
