apiVersion: v1
kind: Secret
metadata:
    name: metrics-grafana
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:FxvMEV8=,iv:87b4fNPktj5OLLiURM4mIaU75NXYY3FYfgiaHi9bLGI=,tag:xFe467pwu0SgCZ7B68JsWA==,type:str]
    admin-password: ENC[AES256_GCM,data:EfpSpKqxyfxDu7fnF1m7DhgHAMZcbxR9i3JE56KRufo=,iv:stLSoxt4a9cnjiNd2FFLky1UWYjTykua0BYD6OZ0wwI=,tag:hgiYPiXLRIZh11UqLLxy8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5amJJUVJwUmx3dmlUc242
            OTBMc2ljNjFpRFpFMjlidDlvVWJxcjFqdXdRCkN0WVBKMVRhL3BrVHY5UXNOTVJ2
            VEt4VnQ5YzVRd2daNWxzRDFFUlhkakUKLS0tIHN0YkVJZXFmOXNDRDB6RWt6V2o1
            ckxDMHNKVnhMclVIVnVrYk93VVJOZW8KK855CIAC2pBm567OFkK10QUCaVupcgNS
            u9M7hLXeZSxyqZjkkxwsdNF9H9wJYqT0HOs03LMp9xqVRs01RuCiKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10j22qkq3gxn7779zyle9d4segrhstevjtjmw8hh0e488qzfu3cpskld2ey
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T20:06:14Z"
    mac: ENC[AES256_GCM,data:Kf0+jcGPYIY4AYM69yWhymX7ze4IeE9Hv6d8n1jp4n00URgOoArCNdt18KbxmYfoFTXNhwpcbrHOxXr5MPA/IOaDfmJvLeq29DmMePhXmFsKGLMNLmZfgIwAYXxMOZAsh+YmPLdI0whQwhxWkChHW32pmq0nh+WdnRI3st4guv0=,iv:cnbYtmNmda4iqN16Do79dfy9JrykuF75u240r3Y/JI8=,tag:cAJ/DfeQPeY8VT3Ds4HfdA==,type:str]
    version: 3.13.3
