apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-credentials
    namespace: immich
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:YqlXnMpGhdqyYzEWQ9/V1kRnLvv2a3qDofPs6b7LP0A=,iv:00sPW8nwLu86RwwqP0eT+S87U+B2lpZKQoFHS/o/4oU=,tag:QJl9pGwZHS/hkcdDixC0xA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWTlJYmJLWFBJSjN4dXdM
            U1RCQS80NmFrdU1sS3Z0RlI3bEhtK1dEcnlJCkV2UklPdFlCdWlvdDZrMjdiSkZG
            VWZ5TFNkbFdtUWtlWnFMVWtUNHBibXMKLS0tIEVzZzFwM3BkOGx0dHJ4WEwzVklX
            Sk1yUWpZbUd1K0hVSENvWUtPUVlNaGsKGsWSmmutHFFEso6P5AMpCO0kHq8kaG5+
            9c+3vpzU1k6stSKlGzxonN+nJC3s6PH8JbXAMGrehjMBLc871lbM7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10j22qkq3gxn7779zyle9d4segrhstevjtjmw8hh0e488qzfu3cpskld2ey
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T20:06:19Z"
    mac: ENC[AES256_GCM,data:LY9p73XGAvqO7VyTY0iNsBxb5kygZS15WiZexjlA7FwXGoPr5h1Fj5cZtKb2/wc1NuK+27vyf8+IM7H0akUqefAyYTkgwDhqy30sfEaod5ZqyxHtlVScy/bqDu3smuhhDSgXDP7Ak2nTVbuXVvM/R9MCuetuJw40m/9kWvxFZPQ=,iv:hK4NzILMnzMrzgtKNwCz/kTpoXsGCYHVguuzdPL9kag=,tag:Wk54QhMaX77pQkxdoKxwZQ==,type:str]
    version: 3.13.3
